name = "naps_towers/mocha"
version = "0.1.0"
description = "a tc to v5.5 client object converter"
authors = ["Primiti_ve", "Ice"]
license = "MIT"
private = true # it's a plugin anyway. why would you need it on pesde?

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
luaulog = { name = "realthx1/luaulog", version = "^0.3.0" }
